services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile  # Make sure this points to your Dockerfile for the client side
    ports:
      - "8081:8081"
      - "8080:8080"
    environment:
      - NODE_ENV=production
