services:
  frontend:
    healthcheck:
      test: [CMD, curl, -f, -k, https://localhost:8443/health]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    build:
      context: ./client # Assuming your frontend code is in a directory called "client"
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - 8443:8443
    volumes:
      - ssl_certs:/etc/nginx/ssl
    depends_on:
      backend:
        condition: service_healthy
    networks:
      app-network:
        aliases:
          - frontend

  backend:
    build:
      context: ./server # Assuming your backend code is in a directory called "server"
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - 8444:8444
    volumes:
      - data:/app/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/aegis.db # Update the database path
      - LOGGING_LEVEL_ORG_HIBERNATE=ERROR
      - LOGGING_LEVEL_ROOT=INFO
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=false
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=when_authorized
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_SLL_ENABLED=true
    healthcheck:
      test: [CMD, curl, -f, -k, https://localhost:8444/actuator/health]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
    networks:
      app-network:
        aliases:
          - backend

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  ssl_certs:
  data:
