export const FILE_TYPE_DESCRIPTIONS = new Map([
  // Text Files
  ["text/plain", "Plain Text"],
  ["text/html", "HTML"],
  ["text/css", "CSS"],
  ["application/javascript", "JavaScript"],
  ["application/json", "JSON"],
  ["application/xml", "XML"],

  // Image Files
  ["image/jpeg", "JPEG"],
  ["image/png", "PNG"],
  ["image/gif", "GIF"],
  ["image/bmp", "BMP"],
  ["image/webp", "WebP"], 
  ["image/svg+xml", "SVG"],
  ["image/tiff", "TIFF"],
  ["image/x-icon", "Icon File"],
  ["image/heic", "HEIC Image"],
["image/heif", "HEIF Image"],
["image/x-xcf", "GIMP Image File (XCF)"],
["image/x-photoshop", "Photoshop File (PSD)"],
["image/vnd.adobe.photoshop", "Photoshop File (PSD)"],
["image/x-pcx", "PCX Image"],
["image/x-tga", "TGA Image"],
["image/x-portable-pixmap", "PPM Image"],
["image/x-portable-bitmap", "PBM Image"],
["image/x-portable-graymap", "PGM Image"],
["image/x-portable-anymap", "PNM Image"],

  // Audio Files
  ["audio/mpeg", "MP3"],
  ["audio/wav", "WAV"],
  ["audio/ogg", "OGG"],
  ["audio/aac", "AAC"],
  ["audio/flac", "FLAC"],
  ["audio/midi", "MIDI"],
  ["audio/x-m4a", "M4A Audio"],
["audio/x-ms-wma", "Windows Media Audio (WMA)"],
["audio/x-aiff", "AIFF Audio"],
["audio/x-wav", "WAV Audio"],
["audio/x-flac", "FLAC Audio"],
["audio/x-matroska", "Matroska Audio (MKA)"],
["audio/x-aac", "AAC Audio"],
["audio/x-midi", "MIDI Audio"],

  // Video Files
  ["video/mp4", "MP4"],
  ["video/webm", "WebM"],
  ["video/ogg", "OGG"],
  ["video/x-msvideo", "AVI"],
  ["video/mpeg", "MPEG"],
  ["video/quicktime", "QuickTime (MOV)"],
  ["video/x-matroska", "Matroska Video (MKV)"],
["video/x-ms-wmv", "Windows Media Video (WMV)"],
["video/x-ms-asf", "Advanced Systems Format (ASF)"],
["video/x-flv", "Flash Video (FLV)"],
["video/x-m4v", "M4V Video"],
["video/x-mpeg2", "MPEG-2 Video"],
["video/x-dv", "DV Video"],
["video/x-f4v", "F4V Video"],
["video/x-ogm", "OGM Video"],

  // Document Files
  ["application/pdf", "PDF"],
  ["application/msword", "Word"],
  ["application/vnd.openxmlformats-officedocument.wordprocessingml.document", "Word"],
  ["application/vnd.ms-excel", "Excel"],
  ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Excel"],
  ["application/vnd.ms-powerpoint", "PowerPoint"],
  ["application/vnd.openxmlformats-officedocument.presentationml.presentation", "PowerPoint"],
  ["application/rtf", "RTF"],
  ["application/vnd.oasis.opendocument.text", "OpenDocument Text (ODT)"],
["application/vnd.oasis.opendocument.spreadsheet", "OpenDocument Spreadsheet (ODS)"],
["application/vnd.oasis.opendocument.presentation", "OpenDocument Presentation (ODP)"],
["application/vnd.oasis.opendocument.graphics", "OpenDocument Graphics (ODG)"],
["application/vnd.apple.pages", "Apple Pages Document"],
["application/vnd.apple.numbers", "Apple Numbers Spreadsheet"],
["application/vnd.apple.keynote", "Apple Keynote Presentation"],
["application/x-iwork-keynote-sffkey", "Keynote Presentation"],
["application/epub+zip", "EPUB eBook"],
["application/x-mobipocket-ebook", "MOBI eBook"],
["application/vnd.fdf", "PDF Form Data (FDF)"],
["application/vnd.ms-project", "Microsoft Project"],
["application/vnd.visio", "Microsoft Visio"],
["application/x-latex", "LaTeX Document"],
["application/x-tex", "TeX Document"],

  // Compressed Files
  ["application/zip", "ZIP"],
  ["application/vnd.rar", "RAR"],
  ["application/gzip", "GZIP"],
  ["application/x-7z-compressed", "7z"],
  ["application/x-tar", "TAR"],
  ["application/x-bzip", "BZIP Archive"],
["application/x-bzip2", "BZIP2 Archive"],
["application/x-rar-compressed", "RAR Archive"],
["application/x-7z-compressed", "7z Archive"],
["application/x-tar", "TAR Archive"],
["application/x-iso9660-image", "ISO Disk Image"],
["application/x-cpio", "CPIO Archive"],
["application/x-lzma", "LZMA Archive"],
["application/x-xz", "XZ Archive"],
["application/x-zstd", "Zstandard Archive"],

  // Code Files
  ["text/x-python", "Python"],
  ["text/x-java-source", "Java Source"],
  ["text/x-c", "C Source"],
  ["text/x-c++src", "C++ Source"],
  ["application/x-sh", "Shell Script"],
["application/x-perl", "Perl Script"],
["application/x-php", "PHP Script"],
["application/x-ruby", "Ruby Script"],
["application/x-java-archive", "Java Archive (JAR)"],
["application/x-python-code", "Python Compiled Code"],
["application/x-csh", "C Shell Script"],
["application/x-tcl", "Tcl Script"],
["application/x-lisp", "Lisp Source Code"],
["application/x-go", "Go Source Code"],
["application/x-rust", "Rust Source Code"],
["application/x-swift", "Swift Source Code"],
["application/x-kotlin", "Kotlin Source Code"],
["application/x-dart", "Dart Source Code"],
["application/x-scala", "Scala Source Code"],
["application/x-haskell", "Haskell Source Code"],
["application/x-erlang", "Erlang Source Code"],
["application/x-elixir", "Elixir Source Code"],
["application/x-vbscript", "VBScript"],
["application/x-powershell", "PowerShell Script"],

  // Application and Executable Files
  ["application/vnd.microsoft.portable-executable", "Executable"],
  ["application/x-apple-diskimage", "Disk Image"],
  ["application/vnd.android.package-archive", "Package"],

  // Font Files
  ["font/ttf", "TTF"],
  ["font/otf", "OTF"],
  ["font/woff", "WOFF"],
  ["font/woff2", "WOFF2"],
  ["application/font-woff", "Web Open Font Format (WOFF)"],
["application/font-woff2", "Web Open Font Format 2 (WOFF2)"],
["application/vnd.ms-fontobject", "Embedded OpenType (EOT)"],
["application/x-font-ttf", "TrueType Font (TTF)"],
["application/x-font-otf", "OpenType Font (OTF)"],
["application/x-font-pcf", "PCF Font"],
["application/x-font-bdf", "BDF Font"],

  // Other Common Types
  ["text/csv", "CSV"],
  ["application/x-yaml", "YAML"],
  ["text/markdown", "Markdown"],
  ["text/calendar", "ICS"],
  ["application/x-msdownload", "Windows Executable (EXE)"],
["application/x-dosexec", "DOS Executable"],
["application/x-ms-installer", "Windows Installer (MSI)"],
["application/x-apple-diskimage", "Apple Disk Image (DMG)"],
["application/x-deb", "Debian Package (DEB)"],
["application/x-rpm", "Red Hat Package Manager (RPM)"],
["application/x-pkcs12", "PKCS #12 Certificate (PFX)"],
["application/x-pkcs7-certificates", "PKCS #7 Certificate"],
["application/x-pkcs7-mime", "PKCS #7 MIME"],
["application/x-pem-file", "PEM Certificate"],
["application/x-virtualbox-vdi", "VirtualBox Disk Image (VDI)"],
["application/x-vmware-vmdk", "VMware Disk Image (VMDK)"],
["application/x-qemu-disk", "QEMU Disk Image"],
["application/x-parallels-disk", "Parallels Disk Image"],
["application/x-iso-image", "ISO Image"],
["application/x-apk", "Android Package (APK)"],
["application/x-ipa", "iOS App Package (IPA)"],
["application/x-crx", "Chrome Extension (CRX)"],
["application/vnd.sketchup.skp", "SketchUp Model (SKP)"],
["application/x-skp", "SketchUp Model (SKP)"],
["application/skp", "SketchUp Model (SKP)"],
]);