# Database setup
spring.datasource.url=jdbc:sqlite:/aegis.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=com.aegis.project.configuration.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# # Https setup
# server.port=8443
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=AegisPassword
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=aegis

# HTTP setup
server.http.port=8080

# Logging
logging.level.root=INFO
logging.level.org.aegis.project=DEBUG