services:
  spring-boot-app:
    build: .
    ports:
      - "8080:8080" # Expose the port 8081, HTTP (client runs on 8080, and they can't overlap)
    volumes:
      - db_data:/app/data/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
