# Use the official Gradle image to build the application
FROM gradle:latest as build

# Set the working directory
WORKDIR /app

# Copy the project source
COPY . .

# Build the project
RUN gradle build --no-daemon --stacktrace

# Create a new stage for the runtime environment
FROM eclipse-temurin:21

# Set environment variables
ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    SPRING_APPLICATION_JSON='{"server":{"ssl":{"enabled":true,"key-store":"classpath:keystore.p12","key-store-password":"AegisPassword","key-alias":"aegis"}}}'

# Copy the keystore
COPY --from=build /app/src/main/resources/* /app/

# Copy the compiled JAR file from the build stage
COPY --from=build /app/build/libs/*.jar /app/app.jar

# Copy the DB
COPY db/aegis.db /app/

# Export the port
EXPOSE 8443

# Run the application
CMD ["java", "-jar", "/app/app.jar"]
